name: 'WP Plugin Check'
description: 'Test your WordPress plugin with Plugin Check'
author: 'Pascal Birchler'
branding:
  color: 'blue'
  icon: 'trending-up'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: false
    default: ${{ github.token }}
  build-dir:
    description: 'Build directory'
    required: false
    default: './'
  checks:
    description: 'Only run specific checks'
    required: false
    default: ''
  exclude-checks:
    description: 'Checks to exclude'
    required: false
    default: ''
  categories:
    description: 'Limit checks to specific categories'
    required: false
    default: ''
  exclude-directories:
    description: 'Exclude certain directories from checks'
    required: false
    default: ''
  ignore-warnings:
    description: 'Ignore warnings'
    required: false
    default: 'false'
  ignore-errors:
    description: 'Ignore errors'
    required: false
    default: 'false'
  include-experimental:
    description: 'Include experimental checks'
    required: false
    default: 'false'
  wp-version:
    description: 'WordPress version to use'
    required: false
    default: 'latest'
runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
      with:
        node-version: '20'

    - name: Setup PHP
      uses: shivammathur/setup-php@2e947f1f6932d141d076ca441d0e1e881775e95b
      with:
        php-version: 'latest'
        coverage: none
        tools: composer

    - name: Install WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        mkdir -p bin
        mv wp-cli.phar bin/wp
        echo "${PWD}/bin" >> $GITHUB_PATH
      shell: bash

    - name: WP-CLI Info
      run: wp cli info
      shell: bash

    - name: Set PLUGIN_DIR
      run: |
        PLUGIN_DIR=$(realpath "$BUILD_DIR")
        echo "PLUGIN_DIR=$PLUGIN_DIR" >> "$GITHUB_ENV"
        
        PLUGIN_SLUG=$(basename $PLUGIN_DIR)
        echo "PLUGIN_SLUG=$PLUGIN_SLUG" >> "$GITHUB_ENV"
      shell: bash
      env:
        BUILD_DIR: ${{ inputs.build-dir }}

    - name: Setup wp-env
      run: |
        touch .wp-env.json
        > .wp-env.json
        echo "{ \"core\": $WP_VERSION, \"port\": 8880, \"testsPort\": 8881, \"plugins\": [ \"$PLUGIN_DIR\", \"https://downloads.wordpress.org/plugin/plugin-check.latest-stable.zip\" ] }" >> .wp-env.json

        npm -g --no-fund i @wordpress/env
        wp-env start --update
      shell: bash
      env:
        WP_VERSION: ${{ inputs.wp-version == 'trunk' && '"WordPress/WordPress#master"' || 'null' }}

    - name: Run Plugin Check
      run: |
        CHECKS="${CHECKS//$'\n'/,}"
        EXCLUDE_CHECKS="${EXCLUDE_CHECKS//$'\n'/,}"
        CATEGORIES="${CATEGORIES//$'\n'/,}"
        EXCLUDE_DIRS="${EXCLUDE_DIRS//$'\n'/,}"
        ADDITIONAL_ARGS="$CHECKS $EXCLUDE_CHECKS $CATEGORIES $IGNORE_WARNINGS $IGNORE_ERRORS $INCLUDE_EXPERIMENTAL $EXCLUDE_DIRS"
        
        # TODO: Install dependencies first, see https://github.com/wordpress/plugin-check-action/issues/66
        wp-env run cli wp plugin activate $PLUGIN_SLUG

        # Debugging information
        wp-env run cli wp plugin list
        wp-env run cli wp plugin list-checks
        wp-env run cli wp plugin list-check-categories

        # Run Plugin Check
        wp-env run cli wp plugin check $PLUGIN_SLUG --format=json $ADDITIONAL_ARGS --require=./wp-content/plugins/plugin-check/cli.php > ${{ runner.temp }}/plugin-check-results.txt
      shell: bash
      env:
        CHECKS: ${{ inputs.checks && format('--checks={0}', inputs.checks) || '' }}
        EXCLUDE_CHECKS: ${{ inputs.exclude-checks && format('--exclude-checks={0}', inputs.exclude-checks) || '' }}
        CATEGORIES: ${{ inputs.categories && format('--categories={0}', inputs.categories) || '' }}
        EXCLUDE_DIRS: ${{ inputs.exclude-directories && format('--exclude-directories={0}', inputs.exclude-directories) || '' }}
        IGNORE_WARNINGS: ${{ inputs.ignore-warnings == 'true' && '--ignore-warnings' || '' }}
        IGNORE_ERRORS: ${{ inputs.ignore-errors == 'true' && '--ignore-errors' || '' }}
        INCLUDE_EXPERIMENTAL: ${{ inputs.include-experimental == 'true' && '--include-experimental' || '' }}

    - name: Process results
      run: |
        node ${{ github.action_path }}/dist/index.js ${{ runner.temp }}/plugin-check-results.txt
      shell: bash
      env:
        INPUT_REPO_TOKEN: ${{ inputs.repo-token }}
