name: 'WP Plugin Check'
description: 'Test your WordPress plugin with Plugin Check'
author: 'Pascal Birchler'
branding:
  color: 'blue'
  icon: 'trending-up'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: false
    default: ${{ github.token }}
  build-dir:
    description: 'Build directory'
    required: false
    default: './'
  checks:
    description: 'Only run specific checks'
    required: false
    default: ''
  exclude-checks:
    description: 'Checks to exclude'
    required: false
    default: ''
  categories:
    description: 'Limit checks to specific categories'
    required: false
    default: ''
  exclude-directories:
    description: 'Exclude certain directories from checks'
    required: false
    default: ''
  ignore-warnings:
    description: 'Ignore warnings'
    required: false
    default: 'false'
  ignore-errors:
    description: 'Ignore errors'
    required: false
    default: 'false'
  include-experimental:
    description: 'Include experimental checks'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
      with:
        node-version: '16'

    - name: Setup PHP
      uses: shivammathur/setup-php@81cd5ae0920b34eef300e1775313071038a53429
      with:
        php-version: 'latest'
        coverage: none
        tools: composer

    - name: Install WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        mkdir -p bin
        mv wp-cli.phar bin/wp
        echo "${PWD}/bin" >> $GITHUB_PATH
      shell: bash

    - name: WP-CLI Info
      run: wp cli info
      shell: bash

    - name: Checkout Plugin Check
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      with:
        repository: 'WordPress/plugin-check'
        path: 'plugin-check'

    - name: Build Plugin Check
      run: |
        composer install
      shell: bash
      working-directory: 'plugin-check'

    - name: Move Plugin Check out of plugin folder
      run: |
        mv plugin-check ${{ runner.temp }}/plugin-check
      shell: bash

    - name: Set PLUGIN_DIR
      run: |
        PLUGIN_DIR=$(realpath "$BUILD_DIR")
        echo "PLUGIN_DIR=$PLUGIN_DIR" >> "$GITHUB_ENV"
        
        PLUGIN_SLUG=$(basename $PLUGIN_DIR)
        echo "PLUGIN_SLUG=$PLUGIN_SLUG" >> "$GITHUB_ENV"
      shell: bash
      env:
        BUILD_DIR: ${{ inputs.build-dir }}

    - name: Setup wp-env
      run: |
        touch .wp-env.json
        > .wp-env.json
        echo "{ \"core\": null, \"port\": 8880, \"testsPort\": 8881, \"plugins\": [ \"$PLUGIN_DIR\", \"${{ runner.temp }}/plugin-check\" ] }" >> .wp-env.json

        npm -g i @wordpress/env
        wp-env start --update
      shell: bash

    - name: Run Plugin Check
      run: |
        CHECKS="${CHECKS//$'\n'/,}"
        CATEGORIES="${CATEGORIES//$'\n'/,}"
        EXCLUDE_DIRS="${EXCLUDE_DIRS//$'\n'/,}"
        ADDITIONAL_ARGS="$CHECKS $CATEGORIES $IGNORE_WARNINGS $IGNORE_ERRORS $INCLUDE_EXPERIMENTAL $EXCLUDE_DIRS"
        wp-env run cli wp plugin list
        wp-env run cli wp plugin check $PLUGIN_SLUG --format=json $ADDITIONAL_ARGS --require=./wp-content/plugins/plugin-check/cli.php > ${{ runner.temp }}/plugin-check-results.txt
      shell: bash
      env:
        CHECKS: ${{ inputs.checks && format('--checks={0}', inputs.checks) || '' }}
        EXCLUDE_CHECKS: ${{ inputs.exclude-checks && format('--exclude-checks={0}', inputs.exclude-checks) || '' }}
        CATEGORIES: ${{ inputs.categories && format('--categories={0}', inputs.categories) || '' }}
        EXCLUDE_DIRS: ${{ inputs.exclude-directories && format('--exclude-directories={0}', inputs.exclude-directories) || '' }}
        IGNORE_WARNINGS: ${{ inputs.ignore-warnings == 'true' && '--ignore-warnings' || '' }}
        IGNORE_ERRORS: ${{ inputs.ignore-errors == 'true' && '--ignore-errors' || '' }}
        INCLUDE_EXPERIMENTAL: ${{ inputs.include-experimental == 'true' && '--include-experimental' || '' }}

    - name: Process results
      run: |
        node ${{ github.action_path }}/dist/index.js ${{ runner.temp }}/plugin-check-results.txt
      shell: bash
      env:
        INPUT_REPO_TOKEN: ${{ inputs.repo-token }}
