export interface CheckResult {
	line: number;
	column: number;
	type: 'WARNING' | 'ERROR';
	code: string;
	message: string;
}

export interface FileResults {
	fileName: string;
	results: CheckResult[];
}

export interface CheckSummary {
	totalIssues: number;
	totalErrors: number;
	totalWarnings: number;
}

export class PRCommentFormatter {
	private fileResults: FileResults[] = [];

	constructor(fileResultsMap?: Map<string, CheckResult[]>) {
		if (fileResultsMap) {
			for (const [fileName, results] of fileResultsMap) {
				if (results.length > 0) {
					this.addFileResults(fileName, results);
				}
			}
		}
	}

	getComment(): string {
		const summary = this.getSummary();

		if (summary.totalIssues === 0) {
			return this.formatSuccessComment();
		}

		return this.formatComment();
	}

	getSummary(): CheckSummary {
		let totalErrors = 0;
		let totalWarnings = 0;

		for (const file of this.fileResults) {
			for (const result of file.results) {
				if (result.type === 'ERROR') {
					totalErrors++;
				} else if (result.type === 'WARNING') {
					totalWarnings++;
				}
			}
		}

		return {
			totalIssues: totalErrors + totalWarnings,
			totalErrors,
			totalWarnings,
		};
	}

	private addFileResults(fileName: string, results: CheckResult[]): void {
		this.fileResults.push({ fileName, results });
	}

	private groupResultsByType(): {
		errors: FileResults[];
		warnings: FileResults[];
	} {
		const errors: FileResults[] = [];
		const warnings: FileResults[] = [];

		for (const file of this.fileResults) {
			const fileErrors = file.results.filter(r => r.type === 'ERROR');
			const fileWarnings = file.results.filter(r => r.type === 'WARNING');

			if (fileErrors.length > 0) {
				errors.push({ fileName: file.fileName, results: fileErrors });
			}

			if (fileWarnings.length > 0) {
				warnings.push({ fileName: file.fileName, results: fileWarnings });
			}
		}

		return { errors, warnings };
	}

	private formatComment(): string {
		const summary = this.getSummary();
		const { errors, warnings } = this.groupResultsByType();

		const sections: string[] = [];

		const statusEmoji = summary.totalErrors > 0 ? '❌' : '⚠️';
		const statusText =
			summary.totalErrors > 0 ? 'Failed' : 'Passed with warnings';
		const statusBadge = `> **${statusEmoji} Status: ${statusText}**`;

		sections.push('# 🔍 WordPress Plugin Check Report', '');
		sections.push(statusBadge, '');
		sections.push('## 📊 Report', '');

		sections.push(
			this.tableRow(['🎯 Total Issues', '❌ Errors', '⚠️ Warnings']),
		);
		sections.push(
			this.tableRow([':-------------:', ':-------:', ':---------:']),
		);
		sections.push(
			this.tableRow([
				`**${summary.totalIssues}**`,
				`**${summary.totalErrors}**`,
				`**${summary.totalWarnings}**`,
			]),
		);

		sections.push('', '---', '');

		if (errors.length > 0) {
			sections.push(this.formatErrors(errors));
			sections.push('', '---', '');
		}

		if (warnings.length > 0) {
			sections.push(this.formatWarnings(warnings));
			sections.push('', '---', '');
		}

		sections.push(
			'🤖 Generated by [WordPress Plugin Check Action](https://github.com/WordPress/plugin-check-action) • Learn more about [Plugin Check](https://wordpress.org/plugins/plugin-check/)',
		);

		return sections.join('\n');
	}

	private formatSuccessComment(): string {
		const sections: string[] = [];

		sections.push('# ✅ WordPress Plugin Check Report', '');
		sections.push('> **✅ Status: Passed**', '');
		sections.push('## 📊 Report', '');
		sections.push('All checks passed! No errors or warnings found.', '');
		sections.push('---', '');
		sections.push(
			'🤖 Generated by [WordPress Plugin Check Action](https://github.com/WordPress/plugin-check-action) • Learn more about [Plugin Check](https://wordpress.org/plugins/plugin-check/)',
		);

		return sections.join('\n');
	}

	private formatErrors(errors: FileResults[]): string {
		if (errors.length === 0) {
			return '';
		}

		const sections = errors.map(file => {
			const count = file.results.length;
			const plural = count === 1 ? 'error' : 'errors';

			return `<details>
<summary>📁 <strong>${file.fileName}</strong> (${count} ${plural})</summary>

${this.formatResultsTable(file.results)}

</details>`;
		});

		const totalErrors = errors.reduce((sum, f) => sum + f.results.length, 0);

		return `## ❌ Errors (${totalErrors})

${sections.join('\n\n')}`;
	}

	private formatWarnings(warnings: FileResults[]): string {
		if (warnings.length === 0) {
			return '';
		}

		const sections = warnings.map(file => {
			const count = file.results.length;
			const plural = count === 1 ? 'warning' : 'warnings';

			return `<details>
<summary>📁 <strong>${file.fileName}</strong> (${count} ${plural})</summary>

${this.formatResultsTable(file.results)}

</details>`;
		});

		const totalWarnings = warnings.reduce(
			(sum, f) => sum + f.results.length,
			0,
		);

		return `## ⚠️ Warnings (${totalWarnings})

${sections.join('\n\n')}`;
	}

	private formatResultsTable(results: CheckResult[]): string {
		const header = this.tableRow(['📍 Line', '🔖 Check', '💬 Message']);
		const separator = this.tableRow([':-----:', '--------', '----------']);

		const rows = results.map(result => {
			const line = result.line > 0 ? `\`${result.line}\`` : '`0`';
			return this.tableRow([line, result.code, result.message]);
		});

		return [header, separator, ...rows].join('\n');
	}

	private tableRow(cells: (string | number)[]): string {
		return `| ${cells.join(' | ')} |`;
	}
}
